
export default {
    path:"/movie",
    component:()=>import("views/movie"),
    name:"movie",
    redirect:"/movie/movieBody",
    meta:{
        tabBarFlag:true
    },
    children:[
        {
            path:"movieBody",
            component:()=>import("components/movieBody"),
            name:"moviebody",
            meta:{
                tabBarFlag:true
            }
        },
        {
            path:"movieComming",
            component:()=>import("components/movieComming"),
            name:"moviecomming",
            meta:{
                tabBarFlag:true
            }
        },
        {
            path:"search",
            component:()=>import("views/search"),
            name:"search",
            meta:{
                tabBarFlag:false
            }
        }
    ]
}